
worker_processes 1;

events { worker_connections 1024; }

http {
    server {

        listen 80;
        client_max_body_size 500M;  # Ajustez la taille limite selon vos besoins
        client_body_timeout 60s;          # Délai d'attente pour le corps de la requête
        client_header_timeout 60s;        # Délai d'attente pour les en-têtes de la requête
        send_timeout 60s;                 # Délai d'attente pour envoyer des données au client
        proxy_read_timeout 60s;           # Délai d'attente pour lire une réponse d'un serveur proxy
        proxy_connect_timeout 60s;        # Délai d'attente pour établir une connexion à un serveur proxy
        proxy_send_timeout 60s;           # Délai d'attente pour envoyer des données au serveur proxy
        ssl_session_timeout 5m;           # Délai d'attente pour une session SSL
        keepalive_requests 200;           # Nombre de requêtes par connexion keep-alive
        keepalive_timeout 600s;
        tcp_nopush on;
        tcp_nodelay on;

        # Serve the frontend app
        # Proxy requests to the backend
        location / {
            proxy_pass http://siseb-frontend-pprod:3000;  # Ensure 'backend' is correctly defined in your Docker Compose file
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
            send_timeout 600s;
        }

        # Proxy requests to the backend
        location /api/ {
            proxy_pass http://173.249.45.104:9600;  # Ensure 'backend' is correctly defined in your Docker Compose file
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
            send_timeout 600s;
        }

        # Proxy requests to the stats modules
        location /stat-module/ {
            proxy_pass http://173.249.45.104:9800;  # Ensure 'backend' is correctly defined in your Docker Compose file
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
            send_timeout 600s;
        }

        # Route spécifique pour l'auth (évite /api)
        location /local/ {
            proxy_pass http://siseb-frontend-pprod:3000/local/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;

            # Important pour l'auth
            proxy_redirect off;
            proxy_buffering off;
        }

    }
}



