services:
  siseb-frontend-asin:
    restart: unless-stopped
    container_name: siseb-frontend-asin
    build:
      context: ../..
      dockerfile: docker/dockerfiles/Dockerfile@asin
      tags: ['siseb-frontend-asin']
    networks:
      - siseb

  siseb-nginx-proxy-asin:
    image: nginx:stable-alpine
    container_name: siseb-nginx-proxy-asin
    restart: always
    volumes:
      - ../nginx/nginx.asin.conf:/etc/nginx/nginx.conf
    ports:
      - "9501:80"
    depends_on:
      - siseb-frontend-asin
    networks:
      - siseb

networks:
  siseb:
    external: true
