services:
  siseb-frontend-dev:
    restart: unless-stopped
    container_name: siseb-frontend-dev
    build:
      context: ../..
      dockerfile: docker/dockerfiles/Dockerfile@dev
    networks:
      - siseb

  siseb-nginx-proxy-dev:
    image: nginx:stable-alpine
    container_name: siseb-nginx-proxy-dev
    restart: always
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "9502:80"
    depends_on:
      - siseb-frontend-dev
    networks:
      - siseb

networks:
  siseb:
    external: true
